namespace PacketGenerator.CodeGen;

public class ClientPacketHandlerCode
{
	private string PacketHandlerSource => $@"// generated by RAMG Packet Generator
using System;
using MemoryPack;
using Network.NetCommand;
using Network.Packet.Handler;
using Service.Network;

namespace RAMG.Packets
{{
	[PacketOpcode(RAMG.Packets.Opcode.{_packetType.FullName})]
	public partial class {HandlerName} : IPacketHandler
	{{
		public INetCommand ToCommand(ref MemoryPackReader reader)
		{{
			var command = {_packetType.FullName}.Create();

			{_packetType.FullName}.Deserialize(ref reader, ref command);

			return command;
		}}
	}}
}}
";

	private PacketType _packetType;

	private string packetName;

	private string HandlerName => $"{packetName}PacketHandler";

	public string FileName => $"{HandlerName}.generated.cs";

	public ClientPacketHandlerCode(PacketType packetType)
	{
		_packetType = packetType;
		packetName = packetType.Name.ToTitleCase().Replace("_", string.Empty);
	}

	public string ToSource()
	{
		return PacketHandlerSource;
	}
}
