

namespace PacketGenerator.CodeGen;

public class EnumBody
{
	/// <summary>
	/// 나중에 네임스페이스도 constants 같은곳에서 관리해야할 것.
	/// </summary>
	public static string EnumSourceGlobalBegin => $@"// generated by RAMG Packet Generator
namespace RAMG.Packets
{{";

	public static string EnumSourceGlobalEnd => $@"
}}";

	private string EnumSourceBegin => $@"
	public enum {enumName}
	{{
";

	private string EnumSourceEnd => $@"
	}}";

	private string enumName;

	private string[] enumValues;

	public EnumBody(EnumType enumType)
	{
		enumName = enumType.Name;
		enumValues = enumType.Values;
	}

	public string ToSource()
	{
		var result = EnumSourceBegin;

		for (int i = 0; i < enumValues.Length; i++)
		{
			result += '\t';
			result += '\t';
			result += enumValues[i];

			if (i < enumValues.Length - 1)
			{
				result += ",\n";
			}
		}

		result += EnumSourceEnd;

		return result;
	}
}
