namespace PacketGenerator.CodeGen;

public class ServerPacketHandlerCode
{
	private string PacketHandlerSource => $@"// generated by RAMG Packet Generator
using MemoryPack;
using Network.NetCommand;
using Network.Packet.Handler;

namespace RAMG.Packets
{{
	[PacketOpcode(RAMG.Packets.Opcode.{_packetType.FullName})]
	public partial class {HandlerName} : IPacketHandler
	{{
		public INetCommand ToCommand(ReadOnlySpan<byte> bytes)
		{{
			var command = {_packetType.FullName}.Create();

			MemoryPackSerializer.Deserialize(bytes, ref command);

			return command;
		}}
	}}
}}
";

	private PacketType _packetType;

	private string packetName;

	private string HandlerName => $"{packetName}PacketHandler";

	public string FileName => $"{HandlerName}.generated.cs";

	public ServerPacketHandlerCode(PacketType packetType)
	{
		_packetType = packetType;
		packetName = packetType.Name.ToTitleCase().Replace("_", string.Empty);
	}

	public string ToSource()
	{
		return PacketHandlerSource;
	}
}
